### ISSUE TITLE
Switch reference and data in UI?

### ISSUE THREAD

**Issue by aminnj** [jkguiang/AutoDQM#6]
Maybe it's more natural to have Data on the left and Reference on the right? Looking on the right of the table to get the run number when switching between the run registry and autodqm to evaluate runs feels a bit awkward.
![image](https://user-images.githubusercontent.com/5760027/43223860-4749f6c2-9009-11e8-9654-2e8ef7324ea1.png)

**Comment by A-lxe** [comment]
Sure can do :+1:

**Comment by reasonablytall** [comment]
Changed in #8
